#[project]
#name = "qcd_ml_accel_dirac"
#authors = [
#    {name="Nico Voß"}
#]
#description = "higher performant functions for qcd_ml"


[build-system]
requires = ["torch", "setuptools", "meson-python", "ninja"]
build-backend = "setuptools.build_meta"
