[project]
name = "qcd_ml_accel_dirac"
authors = [
    {name="Nico Voß"}
]
description = "higher performant functions for qcd_ml"
requires-python=">=3.4"
dependencies=['torch']
version="0.0.1"


[build-system]
requires = ["torch", "setuptools"]
build-backend = "setuptools.build_meta"
